export const About = () => {
	return (
		<section id="about">
			<h2>About</h2>
			<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente, numquam minima eos fuga aliquid nisi veniam debitis iusto et corporis porro est ad magnam aperiam maiores, facere, sequi quisquam dolor quas facilis sit quidem similique. Et distinctio magni veniam mollitia nostrum voluptas sed iste ducimus deleniti ullam, qui architecto corrupti, delectus animi eligendi nemo. Corporis autem quisquam quod repudiandae beatae amet eveniet incidunt ab consectetur cumque perferendis enim ad quas, tenetur omnis non nemo a. In, obcaecati consectetur vitae soluta deserunt quod labore ex ipsa minima perspiciatis, porro sapiente officiis eum laboriosam maiores laudantium placeat expedita itaque eaque est atque aut asperiores. Eos officiis natus libero dolore velit magnam quod, facilis officia vitae dolorem. Quisquam esse illo eum repudiandae rerum in earum unde tempore asperiores quis at inventore, natus quaerat sint, placeat atque similique commodi id. Cupiditate qui molestiae ex. Nobis numquam voluptas hic a expedita officia quisquam odit modi fuga vel recusandae unde rem itaque nihil ullam sit nemo, nulla libero, consequatur facere deleniti totam labore. Exercitationem delectus provident a accusamus qui blanditiis nisi illo saepe voluptate excepturi perferendis sapiente iusto, maxime obcaecati velit praesentium vero consequuntur ducimus, dolor ut molestias atque necessitatibus dicta! Laudantium, officiis esse pariatur aut sapiente quaerat aperiam error vel quam aliquam ducimus ipsam voluptatibus laborum suscipit assumenda reprehenderit ipsum dignissimos numquam? Officia aut ea sed commodi repellat corrupti aspernatur, inventore quasi illo incidunt molestiae nostrum quaerat eaque sapiente reiciendis accusantium! Accusamus iusto ad pariatur voluptatibus ex consequatur tempore, facere eveniet atque dolores quibusdam dolorum doloribus recusandae esse magni, vitae cumque ea unde cupiditate numquam? Placeat ipsam, deleniti blanditiis dolorum quidem optio quae obcaecati. Doloremque possimus, accusamus sunt adipisci veritatis earum quaerat, esse rem dolorum, placeat voluptates ducimus autem accusantium cum voluptatum rerum! Sed, ab alias dignissimos illo corporis fuga rem doloribus, laboriosam, neque adipisci sunt. Rem, iure praesentium. Perspiciatis architecto eaque neque enim dolor! Deleniti repellat, consequatur aut quis natus sapiente quidem consectetur quisquam? Reprehenderit maxime placeat aut. Ab, reprehenderit impedit. Dignissimos veniam cum eveniet vero quasi? Sint voluptatum porro ex veniam repellendus. Cumque odit iusto veritatis quasi debitis doloribus dolorem dolorum nihil eligendi voluptatem non perferendis sunt amet ex aut ea nisi, saepe voluptatibus esse necessitatibus. Asperiores odio dignissimos laborum, enim soluta delectus saepe ipsum ipsa non, mollitia nihil eaque dolorum tenetur magnam est rem deserunt nisi esse aperiam nulla reprehenderit ullam! Possimus maiores omnis itaque blanditiis earum quaerat ea impedit ipsa molestias.</p>
		</section>
	)
}

