	export const Hero = () => {
		return (
			<section id="hero" className="section">
				<div className="container">
				<h1 className="title">Hero</h1>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem aliquam, possimus eveniet praesentium minus enim, voluptates vel soluta assumenda necessitatibus, suscipit corporis sequi quae delectus in accusamus quasi modi non? Deleniti reprehenderit rerum temporibus, at cupiditate voluptates aperiam quibusdam iure. Ad cumque aperiam harum veritatis eaque laborum assumenda dolorum? Sit, hic dolorum exercitationem illo architecto doloremque suscipit dolores rerum esse sapiente illum sunt, quibusdam, fugiat optio praesentium soluta quo dolor culpa maiores. Reiciendis dolor explicabo adipisci? Sit nesciunt obcaecati non corporis delectus minima reiciendis labore eligendi molestiae. Nesciunt sit cumque hic possimus suscipit eos, tempora reiciendis nostrum ducimus excepturi in debitis molestias totam magnam voluptas adipisci incidunt maiores ratione ex eum assumenda animi quaerat nemo? Saepe accusantium minus exercitationem debitis, dolore eaque nobis, culpa voluptatem quo aut labore id animi ducimus possimus quia necessitatibus doloribus ex molestiae excepturi eius magnam modi aliquid. Iste, iusto dolor nisi vero minima tenetur nesciunt facilis, excepturi atque, saepe quibusdam blanditiis cum id porro? Molestias pariatur amet perferendis, deserunt facilis nisi assumenda obcaecati veniam enim minus. Tenetur sed aliquid earum incidunt provident itaque accusamus pariatur expedita, quaerat eveniet facere dicta deleniti corrupti quod eos fugit ipsa nemo consectetur, distinctio necessitatibus doloribus officiis voluptatibus molestias sequi. Suscipit iure ab ipsam, minus omnis quis autem voluptates illum voluptatem id delectus inventore? Qui praesentium repudiandae nisi officiis ex dolores aperiam voluptates quidem saepe at perspiciatis cupiditate possimus, harum sapiente reprehenderit iusto voluptate veniam, error molestiae hic. Velit rem placeat tenetur ratione nesciunt, eveniet saepe, id, quos doloribus quod quisquam ad? Inventore beatae excepturi unde provident ipsam? Animi pariatur dolores enim quos repellat porro quis eveniet tenetur sed sint, earum obcaecati iste voluptates nihil ab eaque hic quia qui magnam? Assumenda nihil saepe fugit corporis nisi dignissimos, eos cupiditate, veritatis aliquam voluptas sapiente, quasi vitae maxime officia tempore culpa.</p>
				</div>
			</section>
		)
	}